-keep class kotlinx.serialization.SerializationException { *; }
-keep class kotlinx.serialization.internal.Platform_commonKt** { *; }
-keep class kotlinx.serialization.SerializersKt** { *; }
-keep class com.rintaroo.mokumokusolo.navigation.AppDestination** { *; }
-keep class androidx.navigation** { *; }
